apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpitfuture-frontend
spec:
  selector:
    matchLabels:
      app: gpitfuture-frontend
  template:
    metadata:
      labels:
        app: gpitfuture-frontend
    spec:
      containers:
      - name: gpitfuture-frontend
        image: gpitfutureaksdev.azurecr.io/nhsd/buying-catalogue-frontend
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 500m
          limits:
            cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: gpitfuture-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: gpitfuture-frontend