apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpitfuture-deployment-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gpitfuture-frontend
  template:
    metadata:
      labels:
        app: gpitfuture-frontend
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: gpitfuture-frontend
        image: gpitfutureaksdev.azurecr.io/nhsd/buying-catalogue-frontend
        ports:
        - containerPort: 3001
        resources:
          requests:
            cpu: 500m
          limits:
            cpu: 1
---        
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  ports:
  - port: 3001
  selector:
    app: gpitfuture-frontend
---
apiVersion: v1
kind: Service
metadata:
  name: gpitfuture-frontend-lb
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: gpitfuture-frontend